/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adsnet.ui;
import java.util.logging.*;
import adsnet.helper.*;
import adsnet.model.PaketInternet;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Arif
 */
public class PaketWindow extends javax.swing.JFrame {
    /**
     * Creates new form PaketWindow
     */
    public PaketWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void showMessage(String message, int type){
        if (type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbSicepat = new javax.swing.JRadioButton();
        rbSikilat = new javax.swing.JRadioButton();
        rbSiflash = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        btDone = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADS.Net");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Pilih Paket");

        rbSicepat.setText("Paket SiCepat");

        rbSikilat.setText("Paket SiKilat");

        rbSiflash.setText("Paket SiFlash");

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("- rp 200.000/Bulan\n\n-Speed up to 4 mbps\n\n- cocok untuk 4-6 orang\n\n- bebas fair usage policy (FUP)\n\n- Biaya pemasangan awal\n   rp 250.000");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("- rp 250.000/Bulan\n\n-Speed up to 6 mbps\n\n- cocok untuk 6-10 orang\n\n- bebas fair usage policy (FUP)\n\n- Biaya pemasangan awal\n   rp 250.000");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("- Rp 150.000/Bulan\n\n-Speed up to 2 mbps\n\n- cocok untuk 2-3 orang\n\n- bebas fair usage policy (FUP)\n\n- Biaya pemasangan awal\n   rp 250.000");
        jScrollPane5.setViewportView(jTextArea5);

        btDone.setText("Done");
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btDone, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(rbSicepat)
                .addGap(123, 123, 123)
                .addComponent(rbSikilat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbSiflash)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSicepat)
                    .addComponent(rbSikilat)
                    .addComponent(rbSiflash))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDone)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
        // TODO add your handling code here:
        
        if(rbSicepat.isSelected()){
            try{
                Connection conn = ConnectionHelper.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM paket_internet WHERE id_paket = 1";
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rs.getString("nama_paket")); 
                    PaketInternet.setHarga_paket(rs.getString("harga_paket"));
                    PaketInternet.setSpeed_paket(rs.getString("speed_paket"));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new MainWindow().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(PaketWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }else if(rbSikilat.isSelected()){
            try{
                Connection conn = ConnectionHelper.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM paket_internet WHERE id_paket = 2";
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rs.getString("nama_paket"));
                    PaketInternet.setHarga_paket(rs.getString("harga_paket"));
                    PaketInternet.setSpeed_paket(rs.getString("speed_paket"));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new MainWindow().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(PaketWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }else if(rbSiflash.isSelected()){
            try{
                Connection conn = ConnectionHelper.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM paket_internet WHERE id_paket = 3";
                ResultSet rs = st.executeQuery(sql);
                
                if(rs.next()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rs.getString("nama_paket"));
                    PaketInternet.setHarga_paket(rs.getString("harga_paket"));
                    PaketInternet.setSpeed_paket(rs.getString("speed_paket"));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new MainWindow().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(PaketWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
        /**
        try{
            Connection conn = ConnectionHelper.getConnection();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM paket_internet WHERE id_paket = ?";
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next()){
                if(rbSicepat.isSelected()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSicepat.getText());
                }else if(rbSikilat.isSelected()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSikilat.getText());
                }else{
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSiflash.getText());
                }
            }
        }catch(SQLException e){
            Logger.getLogger(PaketWindow.class.getName()).log(Level.SEVERE, null, e);
        }
        **/
    }//GEN-LAST:event_btDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaketWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JRadioButton rbSicepat;
    private javax.swing.JRadioButton rbSiflash;
    private javax.swing.JRadioButton rbSikilat;
    // End of variables declaration//GEN-END:variables
}
