/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adsnet.ui;

import adsnet.helper.ConnectionHelper;
import java.sql.*;
import adsnet.manager.PembayaranManager;
import adsnet.model.PaketInternet;
import adsnet.model.PembayaranTambah;
import adsnet.model.Pemesanan;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Arif
 */
public class PembayaranWindow extends javax.swing.JFrame {
    PembayaranTambah pembayaranGlobal;
    String id_pemesanan = Integer.toString(Pemesanan.getId_pemesanan());
    String totalpak = PaketInternet.getHarga_paket();
    String totalpem = Pemesanan.getHarga_paket();
    /**
     * Creates new form PembayaranWindow
     */
    public PembayaranWindow() {
        initComponents();
        setLocationRelativeTo(null);
        tfTotal.setText(totalpak);
        tfTotal.setText(totalpem);
    }
    
    public void showMessage(String message, int type){
        if(type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validasiInput() throws SQLException{
        boolean isCompleted = false;
        PembayaranTambah pt = new PembayaranTambah();
        pt.setTotal_pembayaran(tfTotal.getText());
        //Text Field
//        if (tfTotal.getText().isEmpty()){
//            isCompleted = false;
//            tfTotal.requestFocus();
//        }else{
//            pt.setTotal_pembayaran(tfTotal.getText());
//            isCompleted = true;
//        }
        //Radio Button
        if (rbNonTunai.isSelected()) {
            pt.setJenis_pembayaran(rbNonTunai.getText());
            pt.setJenis_nontunai(cbNonTunai.getSelectedItem().toString());
            isCompleted = true;
        } else if (rbTunai.isSelected()) {
            pt.setJenis_pembayaran(rbTunai.getText());
            isCompleted = true;
        }
        
        pembayaranGlobal = pt;
        if (!isCompleted) {
            showMessage("Silahkan pilih metode pembayaran!", 2);
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        rbNonTunai = new javax.swing.JRadioButton();
        rbTunai = new javax.swing.JRadioButton();
        cbNonTunai = new javax.swing.JComboBox<>();
        btBayar = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADS.Net");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Total Pembayaran");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Metode Pembayaran");

        rbNonTunai.setText("Non-Tunai");

        rbTunai.setText("Tunai");

        cbNonTunai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer Bank", "GoPay", "OVO", "DANA" }));

        btBayar.setText("Bayar");
        btBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBayarActionPerformed(evt);
            }
        });

        btBatal.setText("Batal");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("PEMBAYARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTunai)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbNonTunai)
                        .addGap(30, 30, 30)
                        .addComponent(cbNonTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBayar)
                        .addGap(18, 18, 18)
                        .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbNonTunai)
                    .addComponent(cbNonTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbTunai)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBayar)
                    .addComponent(btBatal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btBatalActionPerformed

    private void btBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBayarActionPerformed
        // TODO add your handling code here:   
        try {
            if (validasiInput()) {
                PembayaranManager.tambahPembayaran(pembayaranGlobal);
                showMessage("Terimakasih sudah menggunakan jasa ADS.Net", 1);
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(PembayaranWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /**
        PembayaranTambah pt = new PembayaranTambah();
        try{
            Connection conn = ConnectionHelper.getConnection();
            PreparedStatement pstmn = conn.prepareStatement("insert into pembayaran (id_pembayaran, "
                + "id_pemesanan, jenis_pembayaran, total_pembayaran) values (?, ?, ?, ?)");
            pstmn.setInt(1, pt.getId_pembayaran());
            pstmn.setInt(2, Pemesanan.getId_pemesanan());
        }catch(SQLException e){
            Logger.getLogger(PembayaranWindow.class.getName()).log(Level.SEVERE, null, e);
        }
        **/
    }//GEN-LAST:event_btBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btBayar;
    private javax.swing.JComboBox<String> cbNonTunai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbNonTunai;
    private javax.swing.JRadioButton rbTunai;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
